### ISSUE TITLE
The example is not generated when the entity is not annotated with OpenApiSchema

### ISSUE THREAD

**Issue by lepresk** [cnizzardini/cakephp-swagger-bake#411]
For an operation the example is not displayed when the entity returned by the response is not annotated with `OpenApiSchema` while the entity is well generated in the `Schemas` part

Excuse my bad English, I am French speaking.

**Comment by cnizzardini** [comment]
Can you provide some example code?

**Comment by ax-cnizzardini** [comment]
I wonder if the latest release caused a regression here. What version are you on?

**Comment by ax-cnizzardini** [comment]
I am also curious if this annotation is necessary:

```php
#[OpenApiResponse(schemaType: "array", schema: Transaction::class)]
```

Defining a response schema should not be necessary for CRUD actions unless you need to do something beyond just listing the db/entity schema. What happens if you remove that attribute @lepresk?

**Comment by cnizzardini** [comment]
I wonder if the latest release caused a regression here. What version are you on @lepresk?

I am also curious if this attribute is necessary:

```php
#[OpenApiResponse(schemaType: "array", schema: Transaction::class)]
```

Defining a response schema should not be necessary for CRUD actions unless you need to do something beyond just listing the db/entity schema. What happens if you remove that attribute @lepresk?

**Comment by cnizzardini** [comment]
Also, you are using an Entity as OpenApiResponse schema. This is not necessary and not the proper use of OpenApiResponse schema. From the docs:

> An FQN describing a custom response schema. The class must have either one or more #[OpenApiSchemaProperty] attribute, implement CustomSchemaInterface or both.

https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/docs/attributes.md#openapiresponse

**Comment by lepresk** [comment]
> I wonder if the latest release caused a regression here. What version are you on @lepresk?
> 
> I am also curious if this attribute is necessary:
> 
> ```
> #[OpenApiResponse(schemaType: "array", schema: Transaction::class)]
> ```
> 
> Defining a response schema should not be necessary for CRUD actions unless you need to do something beyond just listing the db/entity schema. What happens if you remove that attribute @lepresk?

If I remove this attribute the example appears well, but I get a schema in the response that does not correspond to the structure of my api

```
{
  "collection" : ,
  "data": []
}
```

**Comment by lepresk** [comment]
> cessary and not the proper use of OpenApiRes

Ok, thank you I will create a custom object that better represents my response

**Comment by cnizzardini** [comment]
Yes, if your responses are direct representations of your Entity with no associations and are CRUD actions, then you can just rely on the default behavior to document your sample schema.

If they are not then you have a few options through the OpenApiResponse attribute. One is to add additional associated Entities through https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/docs/attributes.md#Associations and the other is defining custom response schema through https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/docs/attributes.md#Schema

I'd also note that you can use doc blocks instead of this:

```php
#[OpenApiOperation(summary:"Liste des transaction", description:"Recuperé la liste des transaction de l'utilisateur")]
```

with doc blocks you'd do this:

```php
    /**
     * Liste des transaction
     * 
     * Recuperé la liste des transaction de l'utilisateur
     *
     * @return \Cake\Http\Response|null
     */
    public function index(): Response
    {
        // some stuff
     }
```
