### ISSUE TITLE
Version 1.7.7 requires PHP 8

### ISSUE THREAD

**Issue by ArchangelDesign** [cnizzardini/cakephp-swagger-bake#439]
When did this happen?
I just installed in on a new machine and getting a requirements error, I guess I missed that when you released 1.7.7
https://github.com/cnizzardini/cakephp-swagger-bake/blob/v1.7.7/composer.json#L8

**Comment by ArchangelDesign** [comment]
I switched back to 1.7.6 for now so no rush on this

**Comment by cnizzardini** [comment]
Woof! Something must have gotten messed up when I was switching between branches / php versions locally.

**Comment by cnizzardini** [comment]
> I switched back to 1.7.6 for now so no rush on this

Like hell lol! That was a bad booboo. Glad I read this before going out drinking. I didn't change the default branch to create the release from so it created it from master instead of v1.next.

I deleted v1.7.7 release and recreated it from the correct branch. Never tried doing that before so lemme know if it works.

**Comment by ArchangelDesign** [comment]
yeah, I can only imagine the frustration :) 
and I think it was there for quite a few days, I should have checked that after updating but I ran tests on my 8.1 machine. My bad.
Updated and (this time) tested, all good.
